name: Bug Report
description: Report unexpected behavior in foundational models or architecture limits.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        *Thank you for reporting a bug and helping build a stronger Foundation.*
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: |
        How can we reproduce the problem? 
        If applicable, provide a short snippet of code or a Gherkin-style behavior step.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How critical is this to the platform execution?
      options:
        - Trivial (Cosmetic / Documentation)
        - Minor (Workaround available)
        - Major (Broken core functionality)
        - Critical (System unrecoverable / State corruption)
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: Environment
      description: Which version of Python, OS, or relevant library versions are you using?
    validations:
      required: true
